# Generated by Django 5.1.2 on 2024-10-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=100)),
                ('dadosPessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='index.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=200)),
                ('dadosPessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='index.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('dadosPessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicao', to='index.dadospessoais')),
            ],
        ),
    ]
